rvm:
  - 1.9.2
  - 1.9.3
before_script:
  - cp spec/contactology.example.yml spec/contactology.yml
script:
  - bundle exec rspec spec
notifications:
  email:
    on_success: change
    on_failure: always
